# Generated by Django 2.2.dev20181008190602 on 2018-10-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filtered_Tweets',
            fields=[
                ('Id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('User_name', models.CharField(max_length=125)),
                ('Screen_name', models.CharField(max_length=125)),
                ('tweet_date', models.DateField()),
                ('retweet_count', models.IntegerField()),
                ('User_mentions', models.CharField(max_length=125)),
                ('tweet_text', models.TextField(max_length=256)),
                ('Url_text', models.URLField()),
                ('followers', models.IntegerField()),
                ('favorites', models.IntegerField()),
                ('friends', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='KeyWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('Id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('User_name', models.CharField(max_length=125)),
                ('Screen_name', models.CharField(max_length=125)),
                ('tweet_date', models.DateField()),
                ('retweet_count', models.IntegerField()),
                ('User_mentions', models.CharField(max_length=125)),
                ('tweet_text', models.TextField(max_length=256)),
                ('Url_text', models.URLField()),
                ('followers', models.IntegerField()),
                ('favorites', models.IntegerField()),
                ('friends', models.IntegerField()),
            ],
        ),
    ]
