# Generated by Django 2.2.dev20181008190602 on 2018-10-14 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=125)),
                ('Screen_name', models.CharField(max_length=125)),
                ('tweet_length', models.IntegerField()),
                ('tweet_date', models.DateField()),
                ('retweet_count', models.IntegerField()),
                ('User_mentions', models.CharField(max_length=125)),
                ('tweet_text', models.TextField(max_length=256)),
                ('Url_text', models.URLField()),
            ],
        ),
    ]
