# Generated by Django 2.2.dev20181008190602 on 2018-10-14 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets',
            name='id',
        ),
        migrations.AddField(
            model_name='tweets',
            name='Id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
