# Generated by Django 2.2.dev20181008190602 on 2018-10-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterApi', '0002_auto_20181014_0340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filtered_Tweets',
            fields=[
                ('Id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('User_name', models.CharField(max_length=125)),
                ('Screen_name', models.CharField(max_length=125)),
                ('tweet_length', models.IntegerField()),
                ('tweet_date', models.DateField()),
                ('retweet_count', models.IntegerField()),
                ('User_mentions', models.CharField(max_length=125)),
                ('tweet_text', models.TextField(max_length=256)),
                ('Url_text', models.URLField()),
            ],
        ),
    ]
